import { Header } from "@/components/header";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import { Container } from "@/components/container";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My-first-web3-page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
          <main className="pt-navigation-height bg-page-gradient">
            {children}
          </main>

          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
